WINDOW_WIDTH = 1050
WINDOW_HEIGHT = 750

FIELD_WITH_PARAMETERS_WIDTH = 250
FIELD_WITH_PARAMETERS_HEIGHT = 300
FIELD_WITH_PARAMETERS_BUTTON_PADY = 3
FIELD_WITH_PARAMETERS_SPINBOX_WIDTH = 10
FIELD_WITH_PARAMETERS_LABEL_WIDTH = 13

WORKING_AREA_SIZE = 750

CANVAS_SIZE = 700
